
# [START gae_python37_custom_runtime]
runtime: python38
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    python_version: 3
manual_scaling:
    instances: 1
#entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
# [END gae_python37_custom_runtime]
